name: sleevie test
favicon: null
layout_spectrum: 0.65825
typography_spectrum: 0.5106082670390606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafbfd'
    - '#000000'
    - '#ffbae1'
    - '#769ab3'
    - '#0079c1'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.11172328144311905
purpose: []
